### ISSUE TITLE
gzip support

### ISSUE THREAD

**Issue by bndw** [s3ththompson/new-work#11]
Awesome project!

I'm trying to add [a site](https://camrindengel.com) that returns `gzip` compressed data, however I'm unable find any element selectors that work. I suspect this may be related to the gzipped data.

Looking at the [request](https://github.com/request/request#examples) package you're using it appears that `gzip` must be explicitly enabled on a per-request basis:

> For backwards-compatibility, response compression is not supported by default. To accept gzip-compressed responses, set the `gzip` option to true. Note that the body data passed through request is automatically decompressed while the response object is unmodified and will contain compressed data if the server sent a compressed response.
```js
var request = require('request')
  request(
    { method: 'GET'
    , uri: 'http://www.google.com'
    , gzip: true
    }
  , function (error, response, body) {
      // body is the decompressed response body
      console.log('server encoded the data as: ' + (response.headers['content-encoding'] || 'identity'))
      console.log('the decoded data is: ' + body)
    }
  )
  .on('data', function(data) {
    // decompressed data as it is received
    console.log('decoded chunk: ' + data)
  })
  .on('response', function(response) {
    // unmodified http.IncomingMessage object
    response.on('data', function(data) {
      // compressed data as it is received
      console.log('received ' + data.length + ' bytes of compressed data')
    })
  })
```

**Comment by s3ththompson** [comment]
Thanks for the fix!

Published `1.2.1` 🎉
